FROM python:3.9
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install python3-pip -y
WORKDIR /work/
RUN pip install jupyter
ENTRYPOINT ["jupyter", "notebook" ]
CMD ["--allow-root", "--ip", "0.0.0.0", "--port", "8888", "--NotebookApp.token='12345"]
